config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
  get 'home/trash_em'
  get 'home/trash_em_all'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def trash_em
        @trash_em = List.where(:completed => true).destroy_all
        redirect_to root_url, notice: 'Tous les éléments cochés ont été supprimés.'
    end

    def trash_em_all
        @trash_em_all = List.all.destroy_all
        redirect_to root_url, notice: 'Tous les éléments ont été supprimés.'
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: "Nouveau matériel ajouté." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: "La liste a bien été mise à jour." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "La liste a bien été supprimée." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Check my shoot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<h2 class="materiel">ajoute ton matériel :</h2>
    <%= render "lists/flash" %>
    <h2 class="checklist">ta checklist :</h2>-->

    <div class="container main">
      <header>
        <a href="https://checkmyshoot.herokuapp.com"><img class="serenade-logo" src="/images/blanccrop.png"></a>
        <h1 style="text-align:center">organise tes tournages, tourne sereinement.</h1>
      </header>

      <%= yield %>
    </div>

  </body>
</html>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: @list) do |f| %>
    <% if @list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>
  
        <ul>
          <% list.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-inline my-2 my-lg-0">
        <%= f.text_field :description, class: "form-control mr-sm-2" %>
        <%= f.submit "Ajouter", class: 'btn btn-outline-secondary my-2 my-lg-0' %>
    </div>

  <% end %>
  

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "checkmyShoot", root_path, class: 'navbar-brand' %>
  <div class="container-fluid">
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
    <%= render 'form_index' %>
    </div>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<%# Add object form %>
<%= form_with(model: @list, class: "add-object-form") do |f| %>
  <h3>ajoute ton matériel :</h3>
  <div class="flex form-field">
    <%= f.text_field :description, placeholder: "Sony A6400 / DJI Ronin SC, ..." %>
    <%= f.submit "Ajouter" %>
  </div>
<% end %>

<%# Delete object form %>
<div class="flex form-field">
  <%= link_to(home_trash_em_path, data: { confirm: 'Êtes-vous sûr ?' }, method: :delete, class: "flex button") do %>
    <p>Tout supprimer</p>
    <img class="trash" src="/images/Trashcan.png">
  <% end %>

  <%= link_to(home_trash_em_all_path, data: { confirm: 'Êtes-vous sûr ?' }, class: "flex button red") do %>
    <p>Supprimer tous les éléments rangés</p>
    <img class="trashall" src="/images/Trashcan.png">
  <% end %>
</div>

<%# Object list %>
<div style="margin-top: 100px">
  <h3>ta checklist :</h3>
  <% @lists.each do |list| %>

    <% if list.completed %> 
      <div class="flex list-elem">
        <%= link_to list.description, edit_list_path(list), class: "elem green" %></td>

        <div class="button green">
          <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => true, :style =>'display:none' %>
            <%= f.submit "Non-rangé", class: "no-style" %>
          <% end %>
        </div>

        <%= link_to 'Supprimer', list, class: 'button red', method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
      </div>

    <% else %>

      <div class="flex list-elem">
        <%= link_to list.description, edit_list_path(list), class: "elem" %></td>

        <div class="button">
          <%= form_for(list) do |f| %>
            <%= f.text_field :description, type: 'hidden' %>
            <%= f.check_box :completed, :checked => true, :style =>'display:none' %>
            <%= f.submit "Ranger", class: "no-style" %>
          <% end %>
        </div>

        <%= link_to 'Supprimer', list, class: 'button red', method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
      </div>
    <% end %>

  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>